id: IDDE507BD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:41:12+00:00'
last_modified: '2022-06-08T10:10:25.665939+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22946
  title: གསུང་འབུམ། ངག་དབང་དཔལ་བཟང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    84D9:
      image_group_id: I1KG12012
      title: ''
      total_pages: 885
      order: 1
      base_file: 84D9.txt
    6E46:
      image_group_id: I1KG12013
      title: ''
      total_pages: 398
      order: 2
      base_file: 6E46.txt
    89CB:
      image_group_id: I1KG12014
      title: ''
      total_pages: 692
      order: 3
      base_file: 89CB.txt
    DDF8:
      image_group_id: I1KG12015
      title: ''
      total_pages: 608
      order: 4
      base_file: DDF8.txt
    9DA9:
      image_group_id: I1KG12016
      title: ''
      total_pages: 876
      order: 5
      base_file: 9DA9.txt
    596E:
      image_group_id: I1KG12017
      title: ''
      total_pages: 568
      order: 6
      base_file: 596E.txt
    D9CA:
      image_group_id: I1KG12018
      title: ''
      total_pages: 566
      order: 7
      base_file: D9CA.txt
    EF6A:
      image_group_id: I1KG12019
      title: ''
      total_pages: 716
      order: 8
      base_file: EF6A.txt
    '3636':
      image_group_id: I1KG12020
      title: ''
      total_pages: 800
      order: 9
      base_file: 3636.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
