id: IDDE507BD
legacy_id: P009319
ocr_import_info:
  bdrc_scan_id: W22946
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:35:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T00:52:14.742851+00:00'
last_modified: 2022-09-02 08:54:07.001134
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22946
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22946
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་དཔལ་བཟང་།
  author: མཁན་པོ་ངག་དགའ
statistics:
  ocr_word_mean_confidence_index: 0.6125463818807536
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I1KG12018:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12018
      total_pages: 566
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG12018.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5182468914126628
    legacy_id: v007
  I1KG12014:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12014
      total_pages: 692
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG12014.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6007562428180321
    legacy_id: v003
  I1KG12013:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12013
      total_pages: 398
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG12013.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6695396934206622
    legacy_id: v002
  I1KG12016:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12016
      total_pages: 876
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG12016.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6154303073123598
    legacy_id: v005
  I1KG12020:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12020
      total_pages: 800
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG12020.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6658508965940408
    legacy_id: v009
  I1KG12015:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12015
      total_pages: 608
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG12015.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5702452020804638
    legacy_id: v004
  I1KG12017:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12017
      total_pages: 568
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG12017.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6573305463108796
    legacy_id: v006
  I1KG12012:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12012
      total_pages: 885
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12012.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6116934548648727
    legacy_id: v001
  I1KG12019:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12019
      total_pages: 716
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG12019.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6640303528001459
    legacy_id: v008
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
